### ISSUE TITLE
1px center border on Ovals is cropped

### ISSUE THREAD

**Issue by ServusJon** [timuric/sketch-slicy#1]
What a great plugin!

I found a bug that ovals with a 1px center border are cropped. When I change the border width and export it again, everything is fine. When I go back to 1px after that, everything looks good.

There seems to be a problem on the initial oval shape with 1px…
![oval-icon 2](https://cloud.githubusercontent.com/assets/783416/3382356/9c837452-fc37-11e3-93d9-3540a17ac916.png)

**Comment by timuric** [comment]
@emokiller89 Thx for the report. To be honest I am not sure why this is happening. If you change the value of the border and set it back to 1, it will be ok. However newly created objects have wrong boundaries coordinates for some reasons. I would ask bohemians regarding this issue, and hopefully fix it soon.

**Comment by timuric** [comment]
@emokiller89 As a quick workaround, try to use border set to outside or inside instead of center

**Comment by ServusJon** [comment]
@timuric cheers mate!
